USE AdventureWorks;
GO

SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET NUMERIC_ROUNDABORT OFF;
GO

CREATE XML INDEX SXML_ProductModel_Instructions_VALUE
ON Production.ProductModel
(
  Instructions
) 
USING XML INDEX PXML_ProductModel_Instructions
FOR VALUE;
GO