//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.832.
// 
#pragma warning disable 1591

namespace Apress.Samples.Sql2008 {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    using System.Data.SqlTypes;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AdvWorksProductBrowserSoap", Namespace="http://tempuri.org")]
    public partial class AdvWorksProductBrowser : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetHtmlCatalogDescriptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductHierarchyOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductPhotoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AdvWorksProductBrowser() {
            this.Url = global::Apress.Samples.Properties.Settings.Default.AWProductBrowser_Sql2008_AdvWorksProductBrowser;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetHtmlCatalogDescriptionCompletedEventHandler GetHtmlCatalogDescriptionCompleted;
        
        /// <remarks/>
        public event GetProductHierarchyCompletedEventHandler GetProductHierarchyCompleted;
        
        /// <remarks/>
        public event GetProductPhotoCompletedEventHandler GetProductPhotoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.orgGetHtmlCatalogDescription", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public xml GetHtmlCatalogDescription([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Data.SqlTypes.SqlInt32 ProductID) {
            object[] results = this.Invoke("GetHtmlCatalogDescription", new object[] {
                        ProductID});
            return ((xml)(results[0]));
        }
        
        /// <remarks/>
        public void GetHtmlCatalogDescriptionAsync(System.Data.SqlTypes.SqlInt32 ProductID) {
            this.GetHtmlCatalogDescriptionAsync(ProductID, null);
        }
        
        /// <remarks/>
        public void GetHtmlCatalogDescriptionAsync(System.Data.SqlTypes.SqlInt32 ProductID, object userState) {
            if ((this.GetHtmlCatalogDescriptionOperationCompleted == null)) {
                this.GetHtmlCatalogDescriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHtmlCatalogDescriptionOperationCompleted);
            }
            this.InvokeAsync("GetHtmlCatalogDescription", new object[] {
                        ProductID}, this.GetHtmlCatalogDescriptionOperationCompleted, userState);
        }
        
        private void OnGetHtmlCatalogDescriptionOperationCompleted(object arg) {
            if ((this.GetHtmlCatalogDescriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHtmlCatalogDescriptionCompleted(this, new GetHtmlCatalogDescriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.orgGetProductHierarchy", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetProductHierarchy() {
            object[] results = this.Invoke("GetProductHierarchy", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductHierarchyAsync() {
            this.GetProductHierarchyAsync(null);
        }
        
        /// <remarks/>
        public void GetProductHierarchyAsync(object userState) {
            if ((this.GetProductHierarchyOperationCompleted == null)) {
                this.GetProductHierarchyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductHierarchyOperationCompleted);
            }
            this.InvokeAsync("GetProductHierarchy", new object[0], this.GetProductHierarchyOperationCompleted, userState);
        }
        
        private void OnGetProductHierarchyOperationCompleted(object arg) {
            if ((this.GetProductHierarchyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductHierarchyCompleted(this, new GetProductHierarchyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.orgGetProductPhoto", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.SqlTypes.SqlBinary GetProductPhoto([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Data.SqlTypes.SqlInt32 ProductID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Data.SqlTypes.SqlBoolean Thumbnail) {
            object[] results = this.Invoke("GetProductPhoto", new object[] {
                        ProductID,
                        Thumbnail});
            return ((System.Data.SqlTypes.SqlBinary)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductPhotoAsync(System.Data.SqlTypes.SqlInt32 ProductID, System.Data.SqlTypes.SqlBoolean Thumbnail) {
            this.GetProductPhotoAsync(ProductID, Thumbnail, null);
        }
        
        /// <remarks/>
        public void GetProductPhotoAsync(System.Data.SqlTypes.SqlInt32 ProductID, System.Data.SqlTypes.SqlBoolean Thumbnail, object userState) {
            if ((this.GetProductPhotoOperationCompleted == null)) {
                this.GetProductPhotoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductPhotoOperationCompleted);
            }
            this.InvokeAsync("GetProductPhoto", new object[] {
                        ProductID,
                        Thumbnail}, this.GetProductPhotoOperationCompleted, userState);
        }
        
        private void OnGetProductPhotoOperationCompleted(object arg) {
            if ((this.GetProductPhotoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductPhotoCompleted(this, new GetProductPhotoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.832")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/sqltypes")]
    public partial class xml {
        
        private System.Xml.XmlNode[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetHtmlCatalogDescriptionCompletedEventHandler(object sender, GetHtmlCatalogDescriptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHtmlCatalogDescriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHtmlCatalogDescriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public xml Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((xml)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetProductHierarchyCompletedEventHandler(object sender, GetProductHierarchyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductHierarchyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductHierarchyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetProductPhotoCompletedEventHandler(object sender, GetProductPhotoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductPhotoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductPhotoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.SqlTypes.SqlBinary Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.SqlTypes.SqlBinary)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591